name: pytorch-database-prep
channels:
  - pytorch
  - conda-forge
  - sdrobert
  - defaults
dependencies:
  - nltk=3.5
  - pip
  - pydrobert-speech
  - pysoundfile
  - python>=3.7
  - pytorch>=1.8.1
  - requests
  - sentencepiece=0.1.95
  - jiwer
  - pip:  # FIXME(sdrobert): Update to conda dep when pydrobert-pytorch releases >0.3.0
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@74a761a"
